const Maintenance = require('../models/Maintenance');

async function checkAndCreateMaintenanceTicket({
  stationId,
  sensorType,
  healthScore,
  failureRisk,
  reason
}) {
  if (healthScore < 70 || failureRisk === 'HIGH' || failureRisk === 'CRITICAL') {
    const existing = await Maintenance.findOne({
      stationId,
      sensorType,
      status: { $in: ['REQUIRED', 'DUE_SOON', 'SCHEDULED'] }
    });

    const priority = healthScore < 50 ? 'P1_CRITICAL' : healthScore < 65 ? 'P2_HIGH' : 'P3_MEDIUM';
    const status = healthScore < 65 ? 'REQUIRED' : 'DUE_SOON';
    const dueDate = new Date(Date.now() + 7 * 24 * 3600 * 1000); // within 7 days

    if (!existing) {
      return await Maintenance.create({
        stationId,
        sensorType,
        status,
        failureRisk,
        priority,
        currentHealth: healthScore,
        recommendedAction: `Inspect ${sensorType} sensor within 7 days. (${reason || 'Degraded health index'})`,
        dueDate,
        notes: `Automatically generated by Weather Sentinel AI Predictive Maintenance Engine.`
      });
    } else {
      // Update existing
      return await Maintenance.findByIdAndUpdate(existing._id, {
        currentHealth: healthScore,
        priority,
        status,
        failureRisk
      });
    }
  }
  return null;
}

module.exports = { checkAndCreateMaintenanceTicket };
